#
#  Author: Hari Sekhon
#  Date: 2024-10-09 02:50:05 +0300 (Wed, 09 Oct 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https///github.com/HariSekhon/Ansible
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                P r o m e t h e u s   N o d e   E x p o r t e r
# ============================================================================ #

---
- hosts: all
  become: yes
  vars:
    node_exporter_version: "{{ node_exporter_version_param | default(latest_version) }}"

  tasks:
    - name: Get the latest version of Node Exporter from GitHub
      uri:
        url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
        return_content: yes
      register: github_release

    - name: Check if latest_release has valid content
      assert:
        that:
          - latest_release is defined
          - latest_release.json is defined
          - latest_release.json.tag_name is defined
        fail_msg: "Failed to fetch latest release data or the expected structure is not found"

    - name: Set the latest version
      set_fact:
        latest_version: "{{ github_release.json.tag_name | regex_replace('^v', '') }}"
      when: latest_release.status == 200

    - name: Download Prometheus Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter to /tmp
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"

    - name: Copy node_exporter binary to /usr/local/bin
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: '0755'

    - name: Copy node_exporter.service to the remote server
      copy:
        src: ./node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start the Node Exporter service
      systemd:
        name: node_exporter
        state: started

    - name: Enable Node Exporter service at boot
      systemd:
        name: node_exporter
        enabled: yes
