#
#  Author: Hari Sekhon
#  Date: 2024-10-09 02:50:05 +0300 (Wed, 09 Oct 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https///github.com/HariSekhon/Ansible
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                              P r o m e t h e u s
# ============================================================================ #

---
- hosts: all
  become: yes
  vars:
      prometheus_version: "{{ prometheus_version_param | default(latest_version) }}"

  tasks:
      - name: Get the latest version of Prometheus from GitHub
        ansible.builtin.uri:
            url: https://api.github.com/repos/prometheus/prometheus/releases/latest
            return_content: yes
        register: github_release

      - name: Set the latest version
        ansible.builtin.set_fact:
            latest_version: "{{ github_release.json.tag_name | regex_replace('^v', '') }}"

      - name: Download Prometheus binary tarball
        ansible.builtin.get_url:
            url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
            dest: /tmp/prometheus.tar.gz

      - name: Extract Prometheus to /tmp
        ansible.builtin.unarchive:
            src: /tmp/prometheus.tar.gz
            dest: /tmp/
            remote_src: yes
            creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"

      - name: Copy Prometheus binary to /usr/local/bin
        ansible.builtin.copy:
            src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
            dest: "/usr/local/bin/prometheus"
            mode: '0755'

      - name: Copy existing Prometheus service file
        ansible.builtin.copy:
            src: "{{ playbook_dir }}/prometheus.service"
            dest: /etc/systemd/system/prometheus.service
            mode: '0644'

      - name: Reload systemd
        ansible.builtin.systemd:
            daemon_reload: yes

      - name: Start Prometheus service
        ansible.builtin.systemd:
            name: prometheus
            state: started

      - name: Enable Prometheus service at boot
        ansible.builtin.systemd:
            name: prometheus
            enabled: yes
