#
#  Author: Hari Sekhon
#  Date: 2024-10-09 05:04:31 +0300 (Wed, 09 Oct 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Ansible
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#           A n s i b l e   P l a y b o o k   S y n t a x   C h e c k
# ============================================================================ #

# Runs a syntax check against all playbook.y*ml files found

---
name: Ansible Playbook Syntax Check

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/playbook.y*ml'
      - .github/workflows/ansible_playbook_syntax_check.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/playbook.y*ml'
      - .github/workflows/ansible_playbook_syntax_check.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  #schedule:
  #  - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Ansible Playbook Syntax Check
    uses: HariSekhon/GitHub-Actions/.github/workflows/ansible-playbook-syntax.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
