#
#  Author: Hari Sekhon
#  Date: 2024-10-09 06:34:51 +0300 (Wed, 09 Oct 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Ansible
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                         S y s t e m d   A n a l y z e
# ============================================================================ #

---
name: Systemd-Analyze Verify

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.service'
      - .github/workflows/systemd-analyze.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.service'
      - .github/workflows/systemd-analyze.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  systemd_analyze_verify:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Systemd-Analyze Verify
    uses: HariSekhon/GitHub-Actions/.github/workflows/systemd-analyze.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
